name: todo
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <4.0.0"


dependencies:
  flutter_bloc: ^8.0.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  dartz: ^0.10.1
  equatable: ^2.0.3
  get_it: ^7.2.0
  http: ^0.13.6
  sqflite: ^2.0.3+1
  intl: ^0.17.0
  path: ^1.8.1
  firebase_core: ^2.24.0
  firebase_auth: ^4.15.0
  cloud_firestore: ^4.13.3
  image_picker: ^1.0.4
  firebase_storage: ^11.5.3
  insta_image_viewer: ^1.0.2
  table_calendar: ^3.0.8
  flutter_date_range_picker: ^0.0.5
  date_format: ^2.0.7



dev_dependencies:
  archive: 
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0
  mocktail: ^0.3.0 
  solid_lints: ^0.0.12
flutter:

  uses-material-design: true

