// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCorEpW_rL_TVCrOpL-W6eMrxARBgWijB4',
    appId: '1:660713384265:web:ee42fd178c70ac2a245298',
    messagingSenderId: '660713384265',
    projectId: 'vzhtodo',
    authDomain: 'vzhtodo.firebaseapp.com',
    storageBucket: 'vzhtodo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxxHFbCwHIi5-UsL4imPAperKccKJrqKM',
    appId: '1:660713384265:android:b4dfb18c2450bee4245298',
    messagingSenderId: '660713384265',
    projectId: 'vzhtodo',
    storageBucket: 'vzhtodo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0Dbdo3-tSPs9WG-onLmH6_3_bl450xwI',
    appId: '1:660713384265:ios:afe9b05426be5aa2245298',
    messagingSenderId: '660713384265',
    projectId: 'vzhtodo',
    storageBucket: 'vzhtodo.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0Dbdo3-tSPs9WG-onLmH6_3_bl450xwI',
    appId: '1:660713384265:ios:afe9b05426be5aa2245298',
    messagingSenderId: '660713384265',
    projectId: 'vzhtodo',
    storageBucket: 'vzhtodo.appspot.com',
    iosBundleId: 'com.example.todo',
  );
}
